<script lang="ts">
	import { BACKEND_URL } from '$lib/utils/constants';
	import axios from 'axios';
	import { onMount } from 'svelte';

	onMount(() => {
		axios.post(`${BACKEND_URL}/wakeup`, null, { timeout: 5000 }).then().catch();
	});
</script>

<div class="main">
	<h1 class="title">GEMINI Castor</h1>
	<p>Castor is the part of the GEMINI 3D Browser that aims to facilitate immersive, real-time collaboration.</p>
	<p>On the <a href="/share">Gallery Page</a> you can find models that have been generated by other users.</p>
	<p>
		<strong>To host a live session</strong>, go to the <i>Live Session</i> tab in the console, enter a name, and click
		the <i>Create Live Session</i> button.
	</p>
	<div class="img">
		<img src="/images/Live Session.png" alt="Img failed to load..." />
		<p>Live Session creation</p>
	</div>
	<p>
		New visitors to the model you are viewing will be prompted to join your live session, and users already working on
		the model will be able to join in the <i>Live Session</i> tab.
	</p>
	<div class="row">
		<div class="img">
			<img src="/images/New Join.png" alt="Img failed to load..." />
			<p>New visitors can join directly...</p>
		</div>
		<div class="img">
			<img src="/images/Manual Join.png" alt="Img failed to load..." />
			<p>or can join later through the <i>Live Session</i> tab</p>
		</div>
	</div>
</div>

<style>
	.main {
		padding: 1em;
	}

	.title {
		margin-bottom: 0.5em;
	}

	.row {
		display: flex;
		flex-direction: row;
	}

	.img {
		margin: 0.25em 0.5em;
	}
</style>
